### ISSUE TITLE
Selectively disable linting, if possible

### ISSUE THREAD

**Issue by diedummydie** [BruceEckel/AtomicKotlinExamples#15]
It would be nice if the AtomicKotlin course could temporarily disable IntelliJ linting in some places. For example, in "var & val" Exercise 1, the "correct" code is:  

```
    var answer = 42
    answer = 43
```

...and the linter complains that "Variable 'answer' initializer is redundant." IntelliJ isn't wrong, but it detracts from the clarity of the lesson.

**Comment by svtk** [comment]
Unfortunately, it's too complicated to disable such inspections completely. But you're right that seeing it at the very beginning of the course is confusing! Added one more 'println' to avoid that https://github.com/svtk/AtomicKotlinCourse/commit/2573f12d1eb3027667bd17eeae60b0f86a816bfa

**Comment by BruceEckel** [comment]
Issue fixed by Svetlana
