### ISSUE TITLE
varandval4, Typo in Task Description

### ISSUE THREAD

**Issue by diedummydie** [BruceEckel/AtomicKotlinExamples#16]
Missing word:

> The icons at the top of the Project Tool Window allow (you) to perform several convenient operations.

Also, in IntelliJ 2019.1, I don't seem to have a 'Navigate | Select in...' option in the menu. (screenshot attached)

![menu](https://user-images.githubusercontent.com/1759544/55490890-86066480-5602-11e9-9607-1c0cc50df111.png)

**Comment by diedummydie** [comment]
Regarding the missing 'Navigate | Select in...' menu option, I have that option in the menu now. I don't know why it didn't appear before. Maybe a [cosmic ray](https://en.wikipedia.org/wiki/Single_event_upset).

**Comment by leiflundberg** [comment]
Hi, 

I think that these are the icons the author means. 


<img width="295" alt="Screenshot 2020-09-25 at 15 13 47" src="https://user-images.githubusercontent.com/41685083/94271453-f1a06800-ff41-11ea-8bc7-59a8b76f33c6.png">

**Comment by svtk** [comment]
> I think that these are the icons the author means.

Yes, exactly!

Added the link to the docs to prevent such confusion (the specific screenshot might change, but the docs will be updated correspondingly if the icons change):
https://github.com/svtk/AtomicKotlinCourse/commit/1f912d4287ad6891a2bac0450faf0e7d5379c492

**Comment by BruceEckel** [comment]
Issue fixed by Svetlana
