### ISSUE TITLE
1.9 Booleans, open/closed logic

### ISSUE THREAD

**Issue by diedummydie** [BruceEckel/AtomicKotlinExamples#17]
If a business closes at hour 20, and the current hour is 20, the business is closed.

In the following line from Booleans2.kt, the second Boolean test should be `<`, not `<=`.
`val isOpen = hour >= open && hour <= closed`

Likewise, in the following line from Booleans3.kt, the second Boolean test should be `>=`, not just `>`.
`val isClosed = hour < open || hour > closed`

**Comment by BruceEckel** [comment]
Fixed similar logic in Summary 1 as well. Thanks.
