### ISSUE TITLE
1.13 Expressions & Statements, Exercise 2: breakpoints

### ISSUE THREAD

**Issue by diedummydie** [BruceEckel/AtomicKotlinExamples#18]
From the Task Description:

> Set breakpoints on lines 4 and 5. [...] Continue the process by clicking on Resume program on the left of the debug window or pressing ⌥⌘R. **Notice how the value of the variable x changes after the assignment.**

```Kotlin
/* 3 */ fun main(args: Array<String>) {
/* 4 */     var x = 1
/* 5 */     x = 2
/* 6 */     println(x)
/* 7 */ }
```

It seems that if I want to see the value of `x` change, I should set breakpoints at lines 5 & 6, rather than at 4 & 5... or just put one at 5 and use the 'Step into' button.

When the debugger stops at line 4, that line has not yet executed, so `x` doesn't exist. When it stops at line 5, only line 4 has executed, so `x` = 1. Resuming execution with no further breakpoints, we never get to see the value of `x` change, since the program immediately finishes execution and terminates.

**Comment by svtk** [comment]
Thanks for pointing it out! I've fixed the line numbers (https://github.com/svtk/AtomicKotlinCourse/commit/1a891f4a41fdfa7529d3e2ea1a15908de7af0385)

**Comment by BruceEckel** [comment]
Issue fixed by Svetlana
