### ISSUE TITLE
1.14 Summary 1, Exercise 2: minor efficiency boost

### ISSUE THREAD

**Issue by diedummydie** [BruceEckel/AtomicKotlinExamples#19]
`while` loop given in solution:

```Kotlin
    while (worker > 0) {
        result += worker % 10
        worker /= 10
        if (worker != 0) {
            result *= 10
        }
    }
```

The check performed inside the `if` is effectively identical to the check performed in the `while` loop, so this can be simplified:

```Kotlin
    while (worker > 0) {
        result *= 10
        result += worker % 10
        worker /= 10
    }
```

The first iteration of `result *= 10` performs no unwanted action since at that point `result` is still initialized to zero.

**Comment by svtk** [comment]
That's a good simplification, thank you! Updated the solution https://github.com/svtk/AtomicKotlinCourse/commit/96e21f612292967b9ae273e82dcd93464e55fd9c

**Comment by BruceEckel** [comment]
Issue fixed by Svetlana
